### ISSUE TITLE
没有rt_list键？

### ISSUE THREAD

**Issue by TerraceCN** [Smart-Hypercube/Qzone-API#6]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Qzone-API\test.py", line 6, in <module>
    print(q.emotion_list(524543577))
  File "C:\Users\Administrator\Desktop\Qzone-API\qzone.py", line 298, in emotion_list
    return list(map(Emotion, l if l else []))
  File "C:\Users\Administrator\Desktop\Qzone-API\qzone.py", line 112, in __init__
    self.parse(data)
  File "C:\Users\Administrator\Desktop\Qzone-API\qzone.py", line 172, in parse
    if 'rtlist' in data and data['rt_list']:
KeyError: 'rt_list'

**Comment by SmartHypercube** [comment]
fixed. thanks
